export interface Product {
  productId: string;
  productName: string;
  productCode: string;
  weight: string;
  MRP: string;
  unitPrice: number;
  Segment: string;
  ProductFamily?: string;
  regularImageURL: string;
  zipperImageURL?: string;
  mediaType?: 'image' | 'video';
  gstPercentage: number;
  boxBunch: number;
  patti: number;
  packet: number;
  newItem: boolean;
  isActive: boolean;
  falvourEn: string;
  falvourHi: string;
  falvourGu: string;
  productNameHi: string;
  productNameGu: string;
  hsnCode: string;
  facings?: number;
  defaultOrderQuantity: number;
  orderBoxBunch?: number;
  orderPatti?: number;
  orderPacket?: number;
}

export const PRODUCTS: Product[] = [
  {
    weight: '16.00',
    unitPrice: 4.5,
    Segment: 'WAFERS',
    regularImageURL: 'assets/images/CrunchemMasalaMastiWafers.jpg',
    productNameHi: '૧૬ગ્રામ*૧૯૨ મસાલા વેફર્સ',
    productNameGu: '१६ग्राम*१९२ मसाला वेफर्स',
    productName: '16GM*192 CRUNCHEM MASALA MASTI WAFERS',
    productId: '01t9B000000FJF1QAO',
    ProductFamily: 'POTATO  WAFERS',
    productCode: '100188',
    patti: 12,
    packet: 1,
    newItem: false,
    MRP: '5',
    isActive: true,
    hsnCode: '20052000',
    gstPercentage: 5.0,
    falvourHi: 'मसाला मस्ती वेफर्स',
    falvourGu: 'મસાલા મસ્તી વેફર્સ',
    falvourEn: 'MASALA MASTI WAFERS',
    facings: 7.0,
    defaultOrderQuantity: 0,
    boxBunch: 192,
  },
  {
    weight: '15.00',
    unitPrice: 4.5,
    Segment: 'WAFERS',
    regularImageURL: 'assets/images/CrunchemMasalaMastiWafers.jpg',
    productNameHi: '૧૫ગ્રામ*૧૯૨ ક્રન્ચેમ પેરીપેરી વેફર્સ',
    productNameGu: '१५ग्राम*१९२ क्रंचेम पेरीपेरी वेफर्स',
    productName: '15GM*192 CRUNCHEM PERI PERI WAFERS',
    productId: '01tHF000003ZTQPYA4',
    ProductFamily: 'POTATO  WAFERS',
    productCode: '100234',
    patti: 12,
    packet: 1,
    newItem: false,
    MRP: '5',
    isActive: true,
    hsnCode: '20052000',
    gstPercentage: 12.0,
    falvourHi: 'પેરી પેરી વેફર્સ',
    falvourGu: 'पेरी पेरी वेफर्स',
    falvourEn: 'PERI PERI WAFERS',
    facings: 18.0,
    defaultOrderQuantity: 0,
    boxBunch: 192,
  },
  {
    weight: '32',
    unitPrice: 8.5,
    Segment: 'WESTERN SNACKS',
    regularImageURL: 'assets/images/CrunchemMasalaMastiWafers.jpg',
    productNameHi: '૩૨ગ્રામ*૧૨૦ ક્રન્ચેમ મસાલા મસ્તી વેફર્સ',
    productNameGu: '३२ग्राम*१२० क्रंचेम मसाला मस्ती वेफर्स',
    productName: '32GM*120 CRUNCHEM MASALA MASTI WAFERS',
    productId: '01tHF000006a5sgYAA',
    ProductFamily: 'POTATO WAFERS',
    productCode: '100256',
    patti: 10,
    packet: 1,
    newItem: false,
    MRP: '10',
    isActive: true,
    hsnCode: '20052000',
    gstPercentage: 5.0,
    falvourHi: 'मसाला मस्ती वेफर्स',
    falvourGu: 'મસાલા મસ્તી વેફર્સ',
    falvourEn: 'MASALA MASTI WAFERS',
    facings: 6.0,
    defaultOrderQuantity: 0,
    boxBunch: 120,
  },
  {
    weight: '65',
    unitPrice: 17.0,
    Segment: 'WAFERS',
    regularImageURL: 'assets/images/CrunchemMasalaMastiWafers.jpg',
    productNameHi: '૬૫ગ્રામ*૭૨ ક્રન્ચેમ મસાલા મસ્તી વેફર્સ',
    productNameGu: '६५ग्राम*७२ क्रंचेम मसाला मस्ती वेफर्स',
    productName: '65GM*72 CRUNCHEM MASALA MASTI WAFERS',
    productId: '01tHF000003ZTYUYA4',
    productCode: '100221',
    patti: 8,
    packet: 1,
    newItem: false,
    MRP: '20',
    isActive: true,
    hsnCode: '20052000',
    gstPercentage: 5.0,
    falvourHi: 'मसाला मस्ती वेफर्स',
    falvourGu: 'મસાલા મસ્તી વેફર્સ',
    falvourEn: 'MASALA MASTI WAFERS',
    facings: 60.0,
    defaultOrderQuantity: 0,
    boxBunch: 72,
  },
  {
    weight: '140',
    unitPrice: 34.0,
    Segment: 'WESTERN SNACKS',
    regularImageURL: 'assets/images/CrunchemMasalaMastiWafers.jpg',
    productNameHi: '૧૪૦ગ્રામ*૨૪ ક્રન્ચેમ મસાલા મસ્તી વેફર્સ',
    productNameGu: '१४०ग्राम*२४ क्रंचेम मसाला मस्ती वेफर्स',
    productName: '140GM*24 CRUNCHEM MASALA MASTI WAFERS',
    productId: '01tHF000006aOAzYAM',
    ProductFamily: 'POTATO WAFERS',
    productCode: '100257',
    patti: 0,
    packet: 1,
    newItem: false,
    MRP: '40',
    isActive: true,
    hsnCode: '20052000',
    gstPercentage: 5.0,
    falvourHi: 'मसाला मस्ती वेफर्स',
    falvourGu: 'મસાલા મસ્તી વેફર્સ',
    falvourEn: 'MASALA MASTI WAFERS',
    facings: 8.0,
    defaultOrderQuantity: 0,
    boxBunch: 24,
  },
  {
    weight: '235',
    unitPrice: 38.25,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Tikha_Mitha_Mix.jpg',
    productNameHi: '૨૩૫ગ્રામ*20 ફરાળી ચેવડો',
    productNameGu: '२३५ग्राम*२० फराली चेवड़ो',
    productName: '235GM*20 FARALI CHEVDO',
    productId: '01t5g000002N0ImAAK',
    ProductFamily: 'FARALI CHEVDO',
    productCode: '101047',
    patti: 0,
    packet: 1,
    newItem: false,
    MRP: '45',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 5.0,
    falvourHi: 'फराली चेवडो',
    falvourGu: 'ફરાળી ચેવડો',
    falvourEn: 'FARALI CHEVDO',
    facings: 41.0,
    defaultOrderQuantity: 0,
    boxBunch: 20,
  },
  {
    weight: '24',
    unitPrice: 4.25,
    Segment: 'PELLETS',
    regularImageURL: 'assets/images/Snack_em-Ponga-Masala.jpg',
    productNameHi: "૨૪ગ્રામ*૧૨૦ સ્નેક'એમ પોંગા મસાલા",
    productNameGu: "२४ग्राम*१२० स्नैक'एम पोंगा मसाला",
    productName: "24GM*120 SNACK'EM PONGA MASALA",
    productId: '01tHF000006a5ssYAA',
    ProductFamily: 'PELLETS',
    productCode: '104847',
    patti: 10,
    packet: 1,
    newItem: false,
    MRP: '5',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 5.0,
    falvourHi: "स्नैक'एम पोंगा मसाला",
    falvourGu: "સ્નેક'એમ પોંગા મસાલા",
    falvourEn: "SNACK'EM PONGA MASALA",
    facings: 129.0,
    defaultOrderQuantity: 0,
    boxBunch: 120,
  },
  {
    weight: '400',
    unitPrice: 72.25,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Shing_Bhujia.jpg',
    productNameHi: '૪૦૦ગ્રામ*૧૦ શીંગ ભુજીયા',
    productNameGu: '४००ग्राम*१० शिंग भुजिया',
    productName: '400GM*10 SHING BHUJIA (NEW)',
    productId: '01t5g000002N0ILAA0',
    ProductFamily: 'PEANUT',
    productCode: '102034',
    patti: 0,
    packet: 1,
    newItem: false,
    MRP: '85',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 12.0,
    falvourHi: 'શિંગ ભુજિયા',
    falvourGu: 'शिंग भुजिया',
    falvourEn: 'SHING BHUJIA',
    facings: 63.0,
    defaultOrderQuantity: 0,
    boxBunch: 10,
  },
  {
    weight: '200',
    unitPrice: 42.5,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/KhariShing.jpg',
    productNameHi: '૨૦૦ગ્રામ*૩૦ ખારી શીંગ',
    productNameGu: '200ग्राम*30 खारी शिंग',
    productName: '200GM*30 KHARI SHING',
    productId: '01tHF000006aOAeYAM',
    ProductFamily: 'PEANUT',
    productCode: '101817',
    patti: 0,
    packet: 1,
    newItem: false,
    MRP: '50',
    isActive: true,
    hsnCode: '20081920',
    gstPercentage: 5.0,
    falvourHi: 'खारी शिंग',
    falvourGu: 'ખારી શિંગ',
    falvourEn: 'KHARI SHING',
    facings: 58.0,
    defaultOrderQuantity: 0,
    boxBunch: 30,
  },
  {
    zipperImageURL: 'assets/images/NavratanMix_Standy.jpg',
    weight: '25.00',
    unitPrice: 4.25,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Navratan_Mix.jpg',
    productNameHi: '૨૫ગ્રામ*૨૪૦ નવરત્ન મિકસ',
    productNameGu: '२५ग्राम*२४० नवरत्न मिक्स',
    productName: '25GM*240 NAVRATAN MIX',
    productId: '01tHF000003oXU2YAM',
    ProductFamily: 'NAVRATAN MIX',
    productCode: '102807',
    patti: 16,
    packet: 0,
    newItem: false,
    MRP: '5',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 12.0,
    falvourHi: 'નવરતન મિક્સ',
    falvourGu: 'नवरतन मिक्स',
    falvourEn: 'NAVRATAN MIX',
    facings: 178.0,
    defaultOrderQuantity: 0,
    boxBunch: 240,
  },
  {
    weight: '24',
    unitPrice: 4.25,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Shing_Bhujia.jpg',
    productNameHi: '૨૪ગ્રામ*૨૮૮ શીંગ ભુજીયા',
    productNameGu: '२४ग्राम*२८८ शिंग भुजिया',
    productName: '24GM*288 SHING BHUJIA',
    productId: '01tHF000006a5sQYAQ',
    ProductFamily: 'PEANUT',
    productCode: '102053',
    patti: 16,
    packet: 1,
    newItem: false,
    MRP: '5',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 5.0,
    falvourHi: 'शिंग भुजिया',
    falvourGu: 'શિંગ ભુજિયા',
    falvourEn: 'SHING BHUJIA',
    facings: 60.0,
    defaultOrderQuantity: 0,
    boxBunch: 288,
  },
  {
    weight: '48',
    unitPrice: 8.5,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Shing_Bhujia.jpg',
    productNameHi: '૪૮ગ્રામ*૧૮૦ શીંગ ભુજીયા',
    productNameGu: '४८ग्राम*१८० शिंग भुजिया',
    productName: '48GM*180 SHING BHUJIA',
    productId: '01tHF000006a5sRYAQ',
    ProductFamily: 'PEANUT',
    productCode: '102054',
    patti: 12,
    packet: 1,
    newItem: false,
    MRP: '10',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 5.0,
    falvourHi: 'शिंग भुजिया',
    falvourGu: 'શિંગ ભુજિયા',
    falvourEn: 'SHING BHUJIA',
    facings: 61.0,
    defaultOrderQuantity: 0,
    boxBunch: 180,
  },
  {
    weight: '400.00',
    unitPrice: 72.25,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Aloo-Sev.gif',
    productNameHi: '૪૦૦ગ્રામ*૧૦ આલૂ સેવ',
    productNameGu: '४००ग्राम*१० आलू सेव',
    productName: '400GM*10 ALOO SEV',
    productId: '01t9B000000FC4jQAG',
    ProductFamily: 'SEV',
    productCode: '102537',
    patti: 0,
    packet: 1,
    newItem: false,
    MRP: '85',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 5.0,
    falvourHi: 'आलू सेव',
    falvourGu: 'આલું સેવ',
    falvourEn: 'ALOO SEV',
    facings: 177.0,
    defaultOrderQuantity: 0,
    boxBunch: 10,
  },
  {
    weight: '200',
    unitPrice: 34.0,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Shing_Bhujia.jpg',
    productNameHi: '૨૦૦ગ્રામ*૨૦ શીંગ ભુજીયા',
    productNameGu: '२००ग्राम*२० शिंग भुजिया',
    productName: '200GM*20 SHING BHUJIA',
    productId: '01tHF000006a5tCYAQ',
    ProductFamily: 'PEANUT',
    productCode: '102055',
    patti: 0,
    packet: 1,
    newItem: false,
    MRP: '40',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 5.0,
    falvourHi: 'शिंग भुजिया',
    falvourGu: 'શિંગ ભુજિયા',
    falvourEn: 'SHING BHUJIA',
    facings: 62.0,
    defaultOrderQuantity: 0,
    boxBunch: 20,
  },
  {
    weight: '400.00',
    unitPrice: 72.25,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Aloo-Sev.gif',
    productNameHi: '૪૦૦ગ્રામ*૧૦ આલૂ સેવ',
    productNameGu: '४००ग्राम*१० आलू सेव',
    productName: '400GM*10 ALOO SEV',
    productId: '01tHF000006HAtzYAG',
    ProductFamily: 'SEV',
    productCode: '102525',
    patti: 0,
    packet: 1,
    newItem: false,
    MRP: '85',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 12.0,
    falvourHi: 'આલું સેવ',
    falvourGu: 'आलू सेव',
    falvourEn: 'ALOO SEV',
    facings: 69.0,
    defaultOrderQuantity: 0,
    boxBunch: 0,
  },
  {
    weight: '400',
    unitPrice: 68.0,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Shing_Bhujia.jpg',
    productNameHi: '૪૦૦ગ્રામ*૧૦ શીંગ ભુજીયા',
    productNameGu: '४००ग्राम*१० शिंग भुजिया',
    productName: '400GM*10 SHING BHUJIA',
    productId: '01tHF000006a5tDYAQ',
    ProductFamily: 'PEANUT',
    productCode: '102056',
    patti: 0,
    packet: 1,
    newItem: false,
    MRP: '80',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 5.0,
    falvourHi: 'शिंग भुजिया',
    falvourGu: 'શિંગ ભુજિયા',
    falvourEn: 'SHING BHUJIA',
    facings: 63.0,
    defaultOrderQuantity: 0,
    boxBunch: 10,
  },
  {
    zipperImageURL: 'assets/images/NavratanMix_Standy.jpg',
    weight: '48',
    unitPrice: 8.5,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Navratan_Mix.jpg',
    productNameHi: '૪૮ગ્રામ*૧૫૦ નવરત્ન મિકસ',
    productNameGu: '४८ग्राम*१५० नवरत्न मिक्स',
    productName: '48GM*150 NAVRATAN MIX',
    productId: '01tHF000005vs16YAA',
    ProductFamily: 'NAVRATAN MIX',
    productCode: '102812',
    patti: 10,
    packet: 1,
    newItem: false,
    MRP: '10',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 5.0,
    falvourHi: 'नवरतन मिक्स',
    falvourGu: 'નવરતન મિક્સ',
    falvourEn: 'NAVRATAN MIX',
    facings: 193.0,
    defaultOrderQuantity: 0,
    boxBunch: 150,
  },
  {
    weight: '24',
    unitPrice: 4.25,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Copy of Copy of Ratlami-Sev.gif',
    productNameHi: '૨૪ગ્રામ*૨૪૦ રતલામી સેવ',
    productNameGu: '२४ग्राम*२४० रतलामी सेव',
    productName: '24GM*240 RATLAMI SEV',
    productId: '01tHF000006a5sZYAQ',
    ProductFamily: 'SEV',
    productCode: '102245',
    patti: 16,
    packet: 1,
    newItem: false,
    MRP: '5',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 5.0,
    falvourHi: 'रतलामी सेव',
    falvourGu: 'રતલામી સેવ',
    falvourEn: 'RATLAMI SEV',
    facings: 82.0,
    defaultOrderQuantity: 0,
    boxBunch: 240,
  },
  {
    weight: '48',
    unitPrice: 8.5,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Aloo-Sev.gif',
    productNameHi: '૪૮ગ્રામ*૧૮૦ આલૂ સેવ',
    productNameGu: '४८ग्राम*१८० आलू सेव',
    productName: '48GM*180 ALOO SEV',
    productId: '01tHF000005vs17YAA',
    ProductFamily: 'SEV',
    productCode: '102535',
    patti: 12,
    packet: 1,
    newItem: false,
    MRP: '10',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 5.0,
    falvourHi: 'आलू सेव',
    falvourGu: 'આલું સેવ',
    falvourEn: 'ALOO SEV',
    facings: 210.0,
    defaultOrderQuantity: 0,
    boxBunch: 180,
  },
  {
    zipperImageURL: 'assets/images/Tikha_Mitha_Mix_Standy.jpg',
    weight: '27',
    unitPrice: 4.25,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Tikha_Mitha_Mix.jpg',
    productNameHi: '૨૭ગ્રામ*૨૪૦ તીખા મીઠા મિકસ',
    productNameGu: '२७ग्राम*२४० तीखा मीठा मिक्स',
    productName: '27GM*240 TIKHA MITHA MIX',
    productId: '01tHF000006qRiOYAU',
    ProductFamily: 'MIXTURE',
    productCode: '102751',
    patti: 16,
    packet: 1,
    newItem: true,
    MRP: '5',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 0.0,
    falvourHi: 'तीखा मीठा मिक्स',
    falvourGu: 'તીખા મીઠા મિક્સ',
    falvourEn: 'TIKHA MITHA MIX',
    defaultOrderQuantity: 0,
    boxBunch: 240,
  },
  {
    zipperImageURL: 'assets/images/Tikha_Mitha_Mix_Standy.jpg',
    weight: '24',
    unitPrice: 4.25,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Tikha_Mitha_Mix.jpg',
    productNameHi: '૨૪ગ્રામ*૨૪૦ તીખા મીઠા મિકસ',
    productNameGu: '२४ग्राम*२४० तीखा मीठा मिक्स',
    productName: '24GM*240 TIKHA MITHA MIX',
    productId: '01tHF000006a5sfYAA',
    ProductFamily: 'MIXTURE',
    productCode: '102748',
    patti: 16,
    packet: 1,
    newItem: false,
    MRP: '5',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 5.0,
    falvourHi: 'तीखा मीठा मिक्स',
    falvourGu: 'તીખા મીઠા મિક્સ',
    falvourEn: 'TIKHA MITHA MIX',
    facings: 71.0,
    defaultOrderQuantity: 0,
    boxBunch: 240,
  },
  {
    zipperImageURL: 'assets/images/Tikha_Mitha_Mix_Standy.jpg',
    weight: '48',
    unitPrice: 8.5,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Tikha_Mitha_Mix.jpg',
    productNameHi: '૪૮ગ્રામ*૧૫૦ તીખામીઠા મિકસ',
    productNameGu: '४८ग्राम*१५० तीखामीठा मिक्स',
    productName: '48GM*150 TIKHA MITHA MIX',
    productId: '01tHF000006a5sTYAQ',
    ProductFamily: 'MIXTURE',
    productCode: '102749',
    patti: 10,
    packet: 1,
    newItem: false,
    MRP: '10',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 5.0,
    falvourHi: 'तीखा मीठा मिक्स',
    falvourGu: 'તીખા મીઠા મિક્સ',
    falvourEn: 'TIKHA MITHA MIX',
    facings: 72.0,
    defaultOrderQuantity: 0,
    boxBunch: 150,
  },
  {
    zipperImageURL: 'assets/images/Tikha_Mitha_Mix_Standy.jpg',
    weight: '230',
    unitPrice: 38.25,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Tikha_Mitha_Mix.jpg',
    productNameHi: '૨૩૦ગ્રામ*૨૦ તીખા મીઠા મિકસ',
    productNameGu: '२३०ग्राम*२० तीखा मीठा मिक्स',
    productName: '230GM*20 TIKHA MITHA MIX',
    productId: '01tHF000006a5tHYAQ',
    ProductFamily: 'MIXTURE',
    productCode: '102750',
    patti: 0,
    packet: 1,
    newItem: false,
    MRP: '45',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 5.0,
    falvourHi: 'तीखा मीठा मिक्स',
    falvourGu: 'તીખા મીઠા મિક્સ',
    falvourEn: 'TIKHA MITHA MIX',
    facings: 73.0,
    defaultOrderQuantity: 0,
    boxBunch: 20,
  },
  {
    zipperImageURL: 'assets/images/Tikha_Mitha_Mix_Standy.jpg',
    weight: '235',
    unitPrice: 34.0,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Tikha_Mitha_Mix.jpg',
    productNameHi: '૨૩૫ગ્રામ*૨૦ તીખા મીઠા મિકસ',
    productNameGu: '२३५ग्राम*२० तीखा मीठा मिक्स',
    productName: '235GM*20 TIKHA MITHA MIX',
    productId: '01tHF000006qRiNYAU',
    ProductFamily: 'MIXTURE',
    productCode: '102753',
    patti: 0,
    packet: 1,
    newItem: false,
    MRP: '40',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 5.0,
    falvourHi: 'तीखा मीठा मिक्स',
    falvourGu: 'તીખા મીઠા મિક્સ',
    falvourEn: 'TIKHA MITHA MIX',
    defaultOrderQuantity: 0,
    boxBunch: 20,
  },
  {
    zipperImageURL: 'assets/images/Tikha_Mitha_Mix_Standy.jpg',
    weight: '500',
    unitPrice: 72.25,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Tikha_Mitha_Mix.jpg',
    productNameHi: '૫૦૦ગ્રામ*૧૦ તીખા મીઠા મિકસ',
    productNameGu: '५००ग्राम*१० तीखा मीठा मिक्स',
    productName: '500GM*10 TIKHA MITHA MIX',
    productId: '01tHF000006qRiPYAU',
    ProductFamily: 'MIXTURE',
    productCode: '102754',
    patti: 0,
    packet: 1,
    newItem: true,
    MRP: '85',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 0.0,
    falvourHi: 'તીખા મીઠા મિક્સ',
    falvourGu: 'तीखा मीठा मिक्स',
    falvourEn: 'TIKHA MITHA MIX',
    defaultOrderQuantity: 0,
    boxBunch: 10,
  },
  {
    zipperImageURL: 'assets/images/NavratanMix_Standy.jpg',
    weight: '27',
    unitPrice: 4.25,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Navratan_Mix.jpg',
    productNameHi: '૨૭ગ્રામ*૨૮૮ નવરત્ન મિકસ',
    productNameGu: '२७ग्राम*२८८ नवरत्न मिक्स',
    productName: '27GM*288 NAVRATAN MIX',
    productId: '01tHF000006qRiQYAU',
    ProductFamily: 'MIXTURE',
    productCode: '102814',
    patti: 16,
    packet: 1,
    newItem: true,
    MRP: '5',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 0.0,
    falvourHi: 'नवरतन मिक्स',
    falvourGu: 'નવરતન મિક્સ',
    falvourEn: 'NAVRATAN MIX',
    defaultOrderQuantity: 0,
    boxBunch: 288,
  },
  {
    zipperImageURL: 'assets/images/NavratanMix_Standy.jpg',
    weight: '24',
    unitPrice: 4.25,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Navratan_Mix.jpg',
    productNameHi: '૨૪ગ્રામ*૨૮૮ નવરત્ન મિકસ',
    productNameGu: '२४ग्राम*२८८ नवरत्न मिक्स',
    productName: '24GM*288 NAVRATAN MIX',
    productId: '01tHF000006a5swYAA',
    ProductFamily: 'MIXTURE',
    productCode: '102811',
    patti: 16,
    packet: 1,
    newItem: false,
    MRP: '5',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 5.0,
    falvourHi: 'नवरतन मिक्स',
    falvourGu: 'નવરતન મિક્સ',
    falvourEn: 'NAVRATAN MIX',
    facings: 78.0,
    defaultOrderQuantity: 0,
    boxBunch: 288,
  },
  {
    zipperImageURL: 'assets/images/NavratanMix_Standy.jpg',
    weight: '54',
    unitPrice: 8.5,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Navratan_Mix.jpg',
    productNameHi: '૫૪ગ્રામ*૧૫૦ નવરત્ન મિકસ',
    productNameGu: '५४ग्राम*१५० नवरत्न मिक्स',
    productName: '54GM*150 NAVRATAN MIX',
    productId: '01tHF000006qRiRYAU',
    ProductFamily: 'MIXTURE',
    productCode: '102815',
    patti: 10,
    packet: 1,
    newItem: true,
    MRP: '10',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 0.0,
    falvourHi: 'नवरतन मिक्स',
    falvourGu: 'નવરતન મિક્સ',
    falvourEn: 'NAVRATAN MIX',
    defaultOrderQuantity: 0,
    boxBunch: 150,
  },
  {
    zipperImageURL: 'assets/images/NavratanMix_Standy.jpg',
    weight: '235',
    unitPrice: 34.0,
    Segment: 'NAMKEEN',
    regularImageURL: 'assets/images/Navratan_Mix.jpg',
    productNameHi: '૨૩૫ગ્રામ*૨૦ નવરત્ન મિકસ',
    productNameGu: '२३५ग्राम*२० नवरत्न मिक्स',
    productName: '235GM*20 NAVRATAN MIX',
    productId: '01tHF000006qRiSYAU',
    ProductFamily: 'MIXTURE',
    productCode: '102816',
    patti: 0,
    packet: 1,
    newItem: true,
    MRP: '40',
    isActive: true,
    hsnCode: '21069099',
    gstPercentage: 0.0,
    falvourHi: 'नवरतन मिक्स',
    falvourGu: 'નવરતન મિક્સ',
    falvourEn: 'NAVRATAN MIX',
    defaultOrderQuantity: 0,
    boxBunch: 20,
  },
];
